projectName = "easyselling"
projectScheme = projectName

lane :tests do
  run_tests(scheme: projectName)
end


lane :deploy do
	setup_ci if ENV['CI']
	match(type: 'appstore', readonly: true)

	update_code_signing_settings(
	    use_automatic_signing: false,
	    path: "#{projectName}.xcodeproj"
	)

    build_app(
        project: "#{projectName}.xcodeproj",
        scheme: projectScheme,
        clean: true,
		export_method: "app-store",
        output_directory: "fastlane/artefacts",
        output_name: "#{projectName}.ipa"
    )

	upload_to_testflight(
		username: ENV["FASTLANE_USERNAME"],
		ipa: "fastlane/artefacts/#{projectName}.ipa",
		skip_waiting_for_build_processing: true,
		skip_submission: true
	)
end
