name: Deploy
on:
  push:
    branches: [ no_branch ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Deploy on TestFlight 
    runs-on: macos-11
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 13.0
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
        bundler-cache: true

    - uses: webfactory/ssh-agent@v0.5.3
      with:
          ssh-private-key: ${{ secrets.MATCH_SSH_KEY }}
            
    - name: Build & Deploy
      run: |
        bundle exec fastlane deploy
      env:
        FASTLANE_USERNAME: '${{ secrets.FASTLANE_USERNAME }}'
        FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
        #FASTLANE_PASSWORD: '${{ secrets.FASTLANE_PASSWORD }}'
        MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
