name: SwiftLint 
on:
  pull_request:

jobs:
  tests:
    name: Verify Linter 
    runs-on: ubuntu-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2

    - name: GitHub Action for SwiftLint with --strict
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict