name: Unit Tests
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    name: Unit Tests 
    runs-on: macos-11
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2

    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 13.0
            
    - name: Install SwiftGen
      run: |
        brew install swiftgen
            
    - name: Run SwiftGen
      run: |
        swiftgen config run
            
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: easyselling.xcodeproj
        scheme: easyselling
        destination: platform=iOS Simulator,OS=latest,name=iPhone 13
        action: test